name: Build site release

on: 
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
    - name: Flutter action
      uses: subosito/flutter-action@v1.1.1
    - name: Set up flutter for web
      run: |
        flutter channel beta
        flutter upgrade
        flutter config --enable-web
    - name: Download dependencies and build project
      run: |
        flutter pub get
        flutter build web --release
    - name: Copy site to root
      run: cp -R -v build/web/* ./
    - name: Stage and commit changes
      run: |
        git config user.name "Publisher"
        git config user.email "publisher@github.com"
        git add .
        git commit -m "Publish web app to Github Pages"
    - name: Push to gh-pages
      uses: ad-m/github-push-action@v0.5.0
      with: 
        github_token: ${{ secrets.GITHUBTOKEN }} 
        branch: gh-pages
        force: true
