name: Build site release

on: 
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
    - name: Flutter action
      uses: subosito/flutter-action@v1.1.1
    - name: Set up flutter for web
      run: |
        flutter channel beta
        flutter upgrade
        flutter config --enable-web
    - name: Download dependencies and build project
      run: |
        flutter pub get
        flutter build web --release
    - name: Copy site to root
      run: cp -R -v build/web/* ./
    - name: Stage changes
      run: git add .
    - name: Commit and push to gh-pages
      uses: github-actions-x/commit@v2.4
      with: 
        github-token: ${{ secrets.GITHUBTOKEN }} 
        push-branch: gh-pages
        commit-message: Publish site to github pages
        rebase: true
